### ISSUE TITLE
Node not connectable, erroneously displaying old version on MN

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/myst-launcher-osx#19]
Describe the bug:
0x2d5e474a2247c1294783ddd91a3dd9d57a231945

Node setup using installer but never able to work. Despite it being downloaded on latest version 1.19.0 It appears to be version 1.14.0 on mystnodes for some reason.

Screenshots:
<img width="737" alt="Screenshot 2022-10-20 at 21 55 34" src="https://user-images.githubusercontent.com/84313603/197087423-03fb2170-f331-47d6-a3d2-9bd9d17aedc3.png">
<img width="787" alt="Screenshot 2022-10-20 at 22 03 16" src="https://user-images.githubusercontent.com/84313603/197087426-33d091b4-37d9-40fd-ab44-5d89339e70b3.png">
<img width="686" alt="Screenshot 2022-10-20 at 22 05 44" src="https://user-images.githubusercontent.com/84313603/197087642-3148e566-fcfa-4f11-9ee4-95fd84c063ad.png">

Environment (please complete the following information):
 - Node version: 1.19.0 (1.14.0 on mystnodes)
 - OS: darwin
 - Your identity (if applicable): 0x2d5e474a2247c1294783ddd91a3dd9d57a231945

Additional context:
Logs:

https://mystnodes.com/support/logs/2022-10-20-7d13a754-507f-4574-b042-5895fa7e218f-mysterium-node.zip480998

**Comment by Zensey** [comment]
@isaackielma 
judging by the logs, the version is really 1.14
looks like a bug

**Comment by Zensey** [comment]
@isaackielma 
it should be fixed now
